package com.librarysystem.view;

import com.librarysystem.model.LibraryModel;
import com.librarysystem.util.Validation;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anuru
 */
public class LibraryApp extends javax.swing.JFrame {

    private java.awt.CardLayout cardLayout;
    private java.awt.CardLayout mainCardLayout;
    private List<LibraryModel> libList;
    
   
    /**
     * Creates new form JavaApp
     */
    public LibraryApp() {
        
        initComponents();
        initializeLayout();
        initializeMainScreenLayout();
        initializeData();
        
        tblAdminLib.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) { // Ensure the event is not a part of multiple changes
            setTextFieldsToSelectedRow();
    }
});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainHome = new javax.swing.JPanel();
        pnlMainHomeLogo = new javax.swing.JLabel();
        pnlHomeDesc = new javax.swing.JPanel();
        lblHomeDescTitle = new javax.swing.JLabel();
        lblHomeDesc = new javax.swing.JLabel();
        pnlLoginScreen = new javax.swing.JPanel();
        lblLoginLogo = new javax.swing.JLabel();
        pnlLoginCenter = new javax.swing.JPanel();
        txtLoginUsername = new javax.swing.JTextField();
        btnLogIn = new javax.swing.JButton();
        pwdLoginPassword = new javax.swing.JPasswordField();
        lblLoginError = new javax.swing.JLabel();
        pnlMainScreen = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlMainAdmin = new javax.swing.JPanel();
        lblAdminDashboard = new javax.swing.JLabel();
        scrPnlAdmin = new javax.swing.JScrollPane();
        tblAdminLib = new javax.swing.JTable();
        lblAdminFunctions = new javax.swing.JLabel();
        txtAdminSearch = new javax.swing.JTextField();
        lblAdminSearch = new javax.swing.JLabel();
        txtLibraryID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtEstdYear = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtTotalBooks = new javax.swing.JTextField();
        comBoxLibraryType = new javax.swing.JComboBox<>();
        comBoxOperatingHours = new javax.swing.JComboBox<>();
        txtStaffCount = new javax.swing.JTextField();
        btnAddLibrary = new javax.swing.JButton();
        lblAdminForm = new javax.swing.JLabel();
        btnUpdateLibrary = new javax.swing.JButton();
        btnDeleteLibrary = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlMainBottom = new javax.swing.JPanel();
        lblMainBottomLogOut = new javax.swing.JLabel();
        lblMainBottomlogo = new javax.swing.JLabel();
        lblMainBottomHome = new javax.swing.JLabel();
        lblMainBottomAdmin = new javax.swing.JLabel();

        pnlMainHome.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainHome.setFocusTraversalPolicyProvider(true);
        pnlMainHome.setMaximumSize(new java.awt.Dimension(1000, 524));
        pnlMainHome.setMinimumSize(new java.awt.Dimension(1000, 524));
        pnlMainHome.setPreferredSize(new java.awt.Dimension(1000, 524));

        pnlMainHomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/Logo.png"))); // NOI18N

        pnlHomeDesc.setBackground(new java.awt.Color(255, 255, 255));
        pnlHomeDesc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 3, true));

        lblHomeDescTitle.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblHomeDescTitle.setForeground(new java.awt.Color(164, 148, 108));
        lblHomeDescTitle.setText("Welcome to the Library Information System");

        lblHomeDesc.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblHomeDesc.setForeground(new java.awt.Color(164, 148, 108));
        lblHomeDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeDesc.setText("<html>Discover a world of knowledge and innovation with our comprehensive Library Information System.<br> Designed to make library management and user experiences seamless, <br>Our platform brings together powerful features that cater to both librarians and readers.<br>Start your journey today and redefine how you experience the library.<br> Whether you're managing the library or exploring its treasures, our Library Information System is here to empower your success.</html>");

        javax.swing.GroupLayout pnlHomeDescLayout = new javax.swing.GroupLayout(pnlHomeDesc);
        pnlHomeDesc.setLayout(pnlHomeDescLayout);
        pnlHomeDescLayout.setHorizontalGroup(
            pnlHomeDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeDescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomeDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeDescLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHomeDescTitle)
                .addGap(327, 327, 327))
        );
        pnlHomeDescLayout.setVerticalGroup(
            pnlHomeDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeDescLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblHomeDescTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(lblHomeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout pnlMainHomeLayout = new javax.swing.GroupLayout(pnlMainHome);
        pnlMainHome.setLayout(pnlMainHomeLayout);
        pnlMainHomeLayout.setHorizontalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(pnlMainHomeLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHomeDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainHomeLayout.setVerticalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlMainHomeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlHomeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnlLoginScreen.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginScreen.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlLoginScreen.setMinimumSize(new java.awt.Dimension(1000, 600));
        pnlLoginScreen.setPreferredSize(new java.awt.Dimension(1000, 600));

        lblLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/Logo.png"))); // NOI18N

        pnlLoginCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Log in to your account", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 24), new java.awt.Color(164, 148, 108))); // NOI18N

        txtLoginUsername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtLoginUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(164, 148, 108))); // NOI18N

        btnLogIn.setBackground(new java.awt.Color(164, 148, 108));
        btnLogIn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log in");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        pwdLoginPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(164, 148, 108))); // NOI18N

        lblLoginError.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(204, 0, 0));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginError.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout pnlLoginCenterLayout = new javax.swing.GroupLayout(pnlLoginCenter);
        pnlLoginCenter.setLayout(pnlLoginCenterLayout);
        pnlLoginCenterLayout.setHorizontalGroup(
            pnlLoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginCenterLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(pnlLoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwdLoginPassword)
                    .addComponent(txtLoginUsername)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginCenterLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        pnlLoginCenterLayout.setVerticalGroup(
            pnlLoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginCenterLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(pwdLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout pnlLoginScreenLayout = new javax.swing.GroupLayout(pnlLoginScreen);
        pnlLoginScreen.setLayout(pnlLoginScreenLayout);
        pnlLoginScreenLayout.setHorizontalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(lblLoginLogo))
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(pnlLoginCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        pnlLoginScreenLayout.setVerticalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(pnlLoginCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Information System");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        pnlMainAdmin.setBackground(new java.awt.Color(255, 255, 255));

        lblAdminDashboard.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        lblAdminDashboard.setForeground(new java.awt.Color(164, 148, 108));
        lblAdminDashboard.setText("Admin Dashboard");

        scrPnlAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true));

        tblAdminLib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Library ID", "Name", "Location", "Library Type", "Estd.Year", "Contact", "Staff Count", "Total Books", "Operating Hours"
            }
        ));
        scrPnlAdmin.setViewportView(tblAdminLib);

        lblAdminFunctions.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblAdminFunctions.setForeground(new java.awt.Color(164, 148, 108));
        lblAdminFunctions.setText("Admin Functions");

        txtAdminSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true));

        lblAdminSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/search.png"))); // NOI18N

        txtLibraryID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLibraryID.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Library ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtLibraryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibraryIDActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtLocation.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLocation.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Location", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });

        txtEstdYear.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtEstdYear.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Estd. Year", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtEstdYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstdYearActionPerformed(evt);
            }
        });

        txtContact.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtContact.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        txtTotalBooks.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtTotalBooks.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Total Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtTotalBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBooksActionPerformed(evt);
            }
        });

        comBoxLibraryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Public", "Private", "Research", "Academic" }));
        comBoxLibraryType.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Library Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        comBoxLibraryType.setOpaque(true);

        comBoxOperatingHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00 - 18:00", "09:00 - 17:00", "17:00 - 02:00", " " }));
        comBoxOperatingHours.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Operating Hours", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        comBoxOperatingHours.setOpaque(true);

        txtStaffCount.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtStaffCount.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Staff Count", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtStaffCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffCountActionPerformed(evt);
            }
        });

        btnAddLibrary.setBackground(new java.awt.Color(164, 148, 108));
        btnAddLibrary.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAddLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLibrary.setText(" Add Library");
        btnAddLibrary.setOpaque(true);
        btnAddLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLibraryActionPerformed(evt);
            }
        });

        lblAdminForm.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblAdminForm.setForeground(new java.awt.Color(164, 148, 108));
        lblAdminForm.setText("Form");

        btnUpdateLibrary.setBackground(new java.awt.Color(164, 148, 108));
        btnUpdateLibrary.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpdateLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateLibrary.setText(" Update Library");
        btnUpdateLibrary.setMaximumSize(new java.awt.Dimension(113, 26));
        btnUpdateLibrary.setMinimumSize(new java.awt.Dimension(113, 26));
        btnUpdateLibrary.setPreferredSize(new java.awt.Dimension(113, 26));
        btnUpdateLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLibraryActionPerformed(evt);
            }
        });

        btnDeleteLibrary.setBackground(new java.awt.Color(164, 148, 108));
        btnDeleteLibrary.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteLibrary.setText("Delete Library");
        btnDeleteLibrary.setMaximumSize(new java.awt.Dimension(113, 26));
        btnDeleteLibrary.setMinimumSize(new java.awt.Dimension(113, 26));
        btnDeleteLibrary.setPreferredSize(new java.awt.Dimension(113, 26));
        btnDeleteLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLibraryActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(164, 148, 108));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainAdminLayout = new javax.swing.GroupLayout(pnlMainAdmin);
        pnlMainAdmin.setLayout(pnlMainAdminLayout);
        pnlMainAdminLayout.setHorizontalGroup(
            pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPnlAdmin)
                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                        .addComponent(lblAdminDashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 523, Short.MAX_VALUE)
                        .addComponent(txtAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainAdminLayout.createSequentialGroup()
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                .addComponent(lblAdminForm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAdminFunctions))
                            .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtLibraryID, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comBoxLibraryType, 0, 165, Short.MAX_VALUE))
                                    .addComponent(txtStaffCount, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                        .addComponent(txtEstdYear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                        .addComponent(txtTotalBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comBoxOperatingHours, 0, 165, Short.MAX_VALUE))))
                                .addGap(182, 182, 182)
                                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdateLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(110, 110, 110)))
                .addContainerGap())
        );
        pnlMainAdminLayout.setVerticalGroup(
            pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comBoxOperatingHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdminSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAdminDashboard)
                                .addComponent(txtAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdminForm)
                            .addComponent(lblAdminFunctions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLibraryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstdYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoxLibraryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStaffCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMainBottom.setBackground(new java.awt.Color(164, 148, 108));

        lblMainBottomLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMainBottomLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainBottomLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/logout.png"))); // NOI18N
        lblMainBottomLogOut.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 1, true), "Log out", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        lblMainBottomLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMainBottomLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainBottomLogOutMouseClicked(evt);
            }
        });

        lblMainBottomlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/output-onlinepngtools (3).png"))); // NOI18N

        lblMainBottomHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainBottomHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/library (1).png"))); // NOI18N
        lblMainBottomHome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 148, 108)), "Home", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        lblMainBottomHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMainBottomHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainBottomHomeMouseClicked(evt);
            }
        });

        lblMainBottomAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainBottomAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/admin.png"))); // NOI18N
        lblMainBottomAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 148, 108)), "Admin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        lblMainBottomAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMainBottomAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainBottomAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMainBottomLayout = new javax.swing.GroupLayout(pnlMainBottom);
        pnlMainBottom.setLayout(pnlMainBottomLayout);
        pnlMainBottomLayout.setHorizontalGroup(
            pnlMainBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainBottomlogo)
                .addGap(260, 260, 260)
                .addComponent(lblMainBottomHome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainBottomAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMainBottomLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMainBottomLayout.setVerticalGroup(
            pnlMainBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMainBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMainBottomLogOut)
                    .addComponent(lblMainBottomHome)
                    .addComponent(lblMainBottomAdmin)
                    .addComponent(lblMainBottomlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMainBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMainBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initializeData(){
        libList = new ArrayList<>();

        // Registering sample students
        registerLibrary(new LibraryModel(1014, "KTM Library", "Kathmandu", "Public", 1885, "9851060670", 350, 4000, "9:00 - 18:00"));
        registerLibrary(new LibraryModel(1028, "Giratee Library", "Kathmandu", "Private", 2024, "9851080670", 300, 4050, "9:00 - 18:00"));
        registerLibrary(new LibraryModel(1039, "Pokhara Library", "Pokhara", "Research", 2000, "985106888", 200, 6000, "9:00 - 18:00"));
    }
    
    private void registerLibrary(LibraryModel library) {
        libList.add(library);
        DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();
        model.addRow(new Object[]{
            library.getLibID(), library.getLibName(), library.getLocation(), library.getLibType(), library.getEstablishedYear(), library.getContactNumber(), library.getStaffCount(), library.getTotalBooks(), library.getOperatingHours()
        });
    }
    
    private void initializeLayout(){
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);
        
        
        getContentPane().add(pnlLoginScreen, "LoginScreen");
        getContentPane().add(pnlMainScreen, "MainScreen");
        
        cardLayout.show(getContentPane(), "LoginScreen");
    }
    private void initializeMainScreenLayout(){
        mainCardLayout = new java.awt.CardLayout();
        pnlMain.setLayout(mainCardLayout);
        
        pnlMain.add(pnlMainHome, "Home");
        pnlMain.add(pnlMainAdmin, "Admin");
        
        mainCardLayout.show(pnlMain, "Home");
        
    }
    
    

// Method to update text fields
    private void setTextFieldsToSelectedRow() {
        DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();
        int selectedRow = tblAdminLib.getSelectedRow();
        if (selectedRow != -1) {
            // Retrieve values from the selected row
            int libID = (int) model.getValueAt(selectedRow, 0);
            String libName = (String) model.getValueAt(selectedRow, 1);
            String location = (String) model.getValueAt(selectedRow, 2);
            String libType = (String) model.getValueAt(selectedRow, 3);
            int establishedYear = (int) model.getValueAt(selectedRow, 4);
            String contactNumber = (String) model.getValueAt(selectedRow, 5);
            int staffCount = (int) model.getValueAt(selectedRow, 6);
            int totalBooks = (int) model.getValueAt(selectedRow, 7);
            String operatingHours = (String) model.getValueAt(selectedRow, 8);

            // Set text fields to these values
            txtLibraryID.setText(String.valueOf(libID));
            txtName.setText(libName);
            txtLocation.setText(location);
            comBoxLibraryType.setSelectedItem(libType);
            txtEstdYear.setText(String.valueOf(establishedYear));
            txtContact.setText(contactNumber);
            txtStaffCount.setText(String.valueOf(staffCount));
            txtTotalBooks.setText(String.valueOf(totalBooks));
            comBoxOperatingHours.setSelectedItem(operatingHours);
        }
    }

    private void txtLibraryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibraryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibraryIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void txtEstdYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstdYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstdYearActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtTotalBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBooksActionPerformed

    private void txtStaffCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffCountActionPerformed

    private void btnAddLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLibraryActionPerformed
            String libId = txtLibraryID.getText();
            String name = txtName.getText();
            String location = txtLocation.getText();
            String libType = (String)comBoxLibraryType.getSelectedItem();
            String estdYear = txtEstdYear.getText();
            String contact = txtContact.getText();
            String staffCount = txtStaffCount.getText();
            String totalBooks = txtTotalBooks.getText();
            String operatingHours = (String)comBoxOperatingHours.getSelectedItem();
            
           boolean valid = true;
            
        if(Validation.isNullOrEmpty(libId)||Validation.isNullOrEmpty(name)||Validation.isNullOrEmpty(location)||Validation.isNullOrEmpty(libType)||Validation.isNullOrEmpty(estdYear)||Validation.isNullOrEmpty(contact)||Validation.isNullOrEmpty(staffCount)||Validation.isNullOrEmpty(totalBooks)||Validation.isNullOrEmpty(operatingHours)){
            JOptionPane.showMessageDialog(this, "Please fill the entire form", "WARNING",JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        else {
            try{
                if(!Validation.isValidLibId(Integer.parseInt(libId))){
                    JOptionPane.showMessageDialog(this, "Id must be 4 digits", "WARNING",JOptionPane.ERROR_MESSAGE);
                    valid = false;
                }
                if(!Validation.isValidName(name)){
                    JOptionPane.showMessageDialog(this, "Only include alphabets in Name","WARNING",JOptionPane.ERROR_MESSAGE);
                    valid = false;
                }
                if(!Validation.isValidLocation(location)){
                    JOptionPane.showMessageDialog(this, "Only include alphabets in Location", "WARNING",JOptionPane.ERROR_MESSAGE);
                    valid = false;
                }
                if(!Validation.isValidContact(contact)){
                    JOptionPane.showMessageDialog(this, "Numbers should be of 10 digits starting from 98", "WARNING",JOptionPane.ERROR_MESSAGE);
                    valid = false;
                }
                if(!Validation.isValidTotalBooks(Integer.parseInt(totalBooks))){
                    JOptionPane.showMessageDialog(this, "Enter valid number of Total Books", "WARNING",JOptionPane.ERROR_MESSAGE);
                    valid = false;
                }
                if(!Validation.isValidStaffCount(Integer.parseInt(staffCount))){
                    JOptionPane.showMessageDialog(this, "Enter valid number Staff Count", "WARNING",JOptionPane.ERROR_MESSAGE);
                    valid = false;
                }
                if(!Validation.isValidEstdYear(Integer.parseInt(estdYear))){
                    JOptionPane.showMessageDialog(this, "Enter a valid year", "WARNING",JOptionPane.ERROR_MESSAGE);
                    valid = false;
                }}
            catch(NumberFormatException e){
                
               JOptionPane.showMessageDialog(this, "Enter numbers where required", "WARNING",JOptionPane.ERROR_MESSAGE);
               valid = false;
            }
            if(valid == true){
                registerLibrary(new LibraryModel(Integer.parseInt(libId), name, location, libType,Integer.parseInt(estdYear), contact, Integer.parseInt(staffCount), Integer.parseInt(totalBooks), operatingHours));
            }
        }   
    }//GEN-LAST:event_btnAddLibraryActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // Get the username and password input
        String username = txtLoginUsername.getText();
        String password = new String(pwdLoginPassword.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            lblLoginError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            
        cardLayout.show(getContentPane(), "MainScreen");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void lblMainBottomLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainBottomLogOutMouseClicked
        cardLayout.show(getContentPane(), "LoginScreen");
    }//GEN-LAST:event_lblMainBottomLogOutMouseClicked

    private void lblMainBottomHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainBottomHomeMouseClicked
        mainCardLayout.show(pnlMain, "Home");
    }//GEN-LAST:event_lblMainBottomHomeMouseClicked

    private void lblMainBottomAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainBottomAdminMouseClicked
        mainCardLayout.show(pnlMain, "Admin");
    }//GEN-LAST:event_lblMainBottomAdminMouseClicked

    private void btnUpdateLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLibraryActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel(); 
        int selectedRow = tblAdminLib.getSelectedRow();
        if (selectedRow != -1) {
            try {
                // Retrieve updated values from text fields and combo boxes
                int libID = Integer.parseInt(txtLibraryID.getText());
                String libName = txtName.getText();
                String location = txtLocation.getText();
                String libType = (String) comBoxLibraryType.getSelectedItem();
                int establishedYear = Integer.parseInt(txtEstdYear.getText());
                String contactNumber = txtContact.getText();
                int staffCount = Integer.parseInt(txtStaffCount.getText());
                int totalBooks = Integer.parseInt(txtTotalBooks.getText());
                String operatingHours = (String) comBoxOperatingHours.getSelectedItem();
             
                
                LibraryModel updatedLibrary = new LibraryModel(libID, libName, location, libType, establishedYear, contactNumber, staffCount, totalBooks, operatingHours);

            // Replace the old object in the ArrayList
                libList.set(selectedRow, updatedLibrary);

                // Update the table row
                model.setValueAt(libID, selectedRow, 0);
                model.setValueAt(libName, selectedRow, 1);
                model.setValueAt(location, selectedRow, 2);
                model.setValueAt(libType, selectedRow, 3);
                model.setValueAt(establishedYear, selectedRow, 4);
                model.setValueAt(contactNumber, selectedRow, 5);
                model.setValueAt(staffCount, selectedRow, 6);
                model.setValueAt(totalBooks, selectedRow, 7);
                model.setValueAt(operatingHours, selectedRow, 8);

                

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter valid data.");
            }
        } 
    

    }//GEN-LAST:event_btnUpdateLibraryActionPerformed

    private void btnDeleteLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLibraryActionPerformed
        int selectedRow = tblAdminLib.getSelectedRow();
        if (selectedRow != -1) { 
            DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();
            model.removeRow(selectedRow);
        }
    }//GEN-LAST:event_btnDeleteLibraryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            txtLibraryID.setText("");
            txtName.setText("");
            txtLocation.setText("");
            txtEstdYear.setText("");
            txtContact.setText("");
            txtStaffCount.setText("");
            txtTotalBooks.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLibrary;
    private javax.swing.JButton btnDeleteLibrary;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnUpdateLibrary;
    private javax.swing.JComboBox<String> comBoxLibraryType;
    private javax.swing.JComboBox<String> comBoxOperatingHours;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAdminDashboard;
    private javax.swing.JLabel lblAdminForm;
    private javax.swing.JLabel lblAdminFunctions;
    private javax.swing.JLabel lblAdminSearch;
    private javax.swing.JLabel lblHomeDesc;
    private javax.swing.JLabel lblHomeDescTitle;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginLogo;
    private javax.swing.JLabel lblMainBottomAdmin;
    private javax.swing.JLabel lblMainBottomHome;
    private javax.swing.JLabel lblMainBottomLogOut;
    private javax.swing.JLabel lblMainBottomlogo;
    private javax.swing.JPanel pnlHomeDesc;
    private javax.swing.JPanel pnlLoginCenter;
    private javax.swing.JPanel pnlLoginScreen;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainAdmin;
    private javax.swing.JPanel pnlMainBottom;
    private javax.swing.JPanel pnlMainHome;
    private javax.swing.JLabel pnlMainHomeLogo;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPasswordField pwdLoginPassword;
    private javax.swing.JScrollPane scrPnlAdmin;
    private javax.swing.JTable tblAdminLib;
    private javax.swing.JTextField txtAdminSearch;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEstdYear;
    private javax.swing.JTextField txtLibraryID;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStaffCount;
    private javax.swing.JTextField txtTotalBooks;
    // End of variables declaration//GEN-END:variables
}
