package com.librarysystem.view;

import com.librarysystem.controller.algorithm.BinarySearch;
import com.librarysystem.controller.algorithm.InsertionSort;
import com.librarysystem.controller.algorithm.MergeSort;
import com.librarysystem.controller.algorithm.SelectionSort;
import com.librarysystem.model.LibraryModel;
import com.librarysystem.util.Validation;
import static com.librarysystem.util.Validation.isNullOrEmpty;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 23048644 Anurup Kharel
 */
public class LibraryApp extends javax.swing.JFrame {

    private java.awt.CardLayout cardLayout;
    private java.awt.CardLayout mainCardLayout;
    private List<LibraryModel> libList;
    
   
    /**
     * Creates new form JavaApp
     */
    public LibraryApp() {
        
        initComponents();
        initializeLayout();
        initializeMainScreenLayout();
        initializeData();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainHome = new javax.swing.JPanel();
        pnlMainHomeLogo = new javax.swing.JLabel();
        pnlHomeDesc = new javax.swing.JPanel();
        lblHomeDescTitle = new javax.swing.JLabel();
        lblHomeDesc = new javax.swing.JLabel();
        pnlLoginScreen = new javax.swing.JPanel();
        lblLoginLogo = new javax.swing.JLabel();
        pnlLoginCenter = new javax.swing.JPanel();
        txtLoginUsername = new javax.swing.JTextField();
        btnLogIn = new javax.swing.JButton();
        pwdLoginPassword = new javax.swing.JPasswordField();
        lblLoginError = new javax.swing.JLabel();
        pnlMainScreen = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlMainAdmin = new javax.swing.JPanel();
        lblAdminDashboard = new javax.swing.JLabel();
        scrPnlAdmin = new javax.swing.JScrollPane();
        tblAdminLib = new javax.swing.JTable();
        lblAdminFunctions = new javax.swing.JLabel();
        txtAdminSearch = new javax.swing.JTextField();
        lblAdminSearch = new javax.swing.JLabel();
        txtLibraryID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtEstdYear = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtTotalBooks = new javax.swing.JTextField();
        comBoxLibraryType = new javax.swing.JComboBox<>();
        comBoxOperatingHours = new javax.swing.JComboBox<>();
        txtStaffCount = new javax.swing.JTextField();
        btnAddLibrary = new javax.swing.JButton();
        lblAdminForm = new javax.swing.JLabel();
        btnUpdateLibrary = new javax.swing.JButton();
        btnDeleteLibrary = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        comBoxSortBy = new javax.swing.JComboBox<>();
        lblSortBy = new javax.swing.JLabel();
        pnlMainBottom = new javax.swing.JPanel();
        lblMainBottomLogOut = new javax.swing.JLabel();
        lblMainBottomlogo = new javax.swing.JLabel();
        lblMainBottomHome = new javax.swing.JLabel();
        lblMainBottomAdmin = new javax.swing.JLabel();

        pnlMainHome.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainHome.setFocusTraversalPolicyProvider(true);
        pnlMainHome.setMaximumSize(new java.awt.Dimension(1000, 524));
        pnlMainHome.setMinimumSize(new java.awt.Dimension(1000, 524));
        pnlMainHome.setPreferredSize(new java.awt.Dimension(1000, 524));

        pnlMainHomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/Logo.png"))); // NOI18N

        pnlHomeDesc.setBackground(new java.awt.Color(255, 255, 255));
        pnlHomeDesc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 3, true));

        lblHomeDescTitle.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblHomeDescTitle.setForeground(new java.awt.Color(164, 148, 108));
        lblHomeDescTitle.setText("Welcome to the Library Information System");

        lblHomeDesc.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblHomeDesc.setForeground(new java.awt.Color(164, 148, 108));
        lblHomeDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeDesc.setText("<html>Discover a world of knowledge and innovation with our comprehensive Library Information System.<br> Designed to make library management and user experiences seamless, <br>Our platform brings together powerful features that cater to both librarians and readers.<br>Start your journey today and redefine how you experience the library.<br> Whether you're managing the library or exploring its treasures, our Library Information System is here to empower your success.</html>");

        javax.swing.GroupLayout pnlHomeDescLayout = new javax.swing.GroupLayout(pnlHomeDesc);
        pnlHomeDesc.setLayout(pnlHomeDescLayout);
        pnlHomeDescLayout.setHorizontalGroup(
            pnlHomeDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeDescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomeDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeDescLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHomeDescTitle)
                .addGap(327, 327, 327))
        );
        pnlHomeDescLayout.setVerticalGroup(
            pnlHomeDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeDescLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblHomeDescTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(lblHomeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout pnlMainHomeLayout = new javax.swing.GroupLayout(pnlMainHome);
        pnlMainHome.setLayout(pnlMainHomeLayout);
        pnlMainHomeLayout.setHorizontalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(pnlMainHomeLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHomeDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainHomeLayout.setVerticalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlMainHomeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlHomeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnlLoginScreen.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginScreen.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlLoginScreen.setMinimumSize(new java.awt.Dimension(1000, 600));
        pnlLoginScreen.setPreferredSize(new java.awt.Dimension(1000, 600));

        lblLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/Logo.png"))); // NOI18N

        pnlLoginCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Log in to your account", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 0, 24), new java.awt.Color(164, 148, 108))); // NOI18N

        txtLoginUsername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtLoginUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), new java.awt.Color(164, 148, 108))); // NOI18N

        btnLogIn.setBackground(new java.awt.Color(164, 148, 108));
        btnLogIn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log in");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        pwdLoginPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), new java.awt.Color(164, 148, 108))); // NOI18N

        lblLoginError.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(204, 0, 0));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginError.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout pnlLoginCenterLayout = new javax.swing.GroupLayout(pnlLoginCenter);
        pnlLoginCenter.setLayout(pnlLoginCenterLayout);
        pnlLoginCenterLayout.setHorizontalGroup(
            pnlLoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginCenterLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(pnlLoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwdLoginPassword)
                    .addComponent(txtLoginUsername)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginCenterLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        pnlLoginCenterLayout.setVerticalGroup(
            pnlLoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginCenterLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(pwdLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout pnlLoginScreenLayout = new javax.swing.GroupLayout(pnlLoginScreen);
        pnlLoginScreen.setLayout(pnlLoginScreenLayout);
        pnlLoginScreenLayout.setHorizontalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(lblLoginLogo))
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(pnlLoginCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        pnlLoginScreenLayout.setVerticalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(pnlLoginCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Information System");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        pnlMainAdmin.setBackground(new java.awt.Color(255, 255, 255));

        lblAdminDashboard.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        lblAdminDashboard.setForeground(new java.awt.Color(164, 148, 108));
        lblAdminDashboard.setText("Admin Dashboard");

        scrPnlAdmin.setBackground(new java.awt.Color(255, 255, 255));
        scrPnlAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true));

        tblAdminLib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Library ID", "Name", "Location", "Library Type", "Estd.Year", "Contact", "Staff Count", "Total Books", "Operating Hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdminLib.getTableHeader().setReorderingAllowed(false);
        tblAdminLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminLibMouseClicked(evt);
            }
        });
        scrPnlAdmin.setViewportView(tblAdminLib);

        lblAdminFunctions.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblAdminFunctions.setForeground(new java.awt.Color(164, 148, 108));
        lblAdminFunctions.setText("Admin Functions");

        txtAdminSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true));

        lblAdminSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/search.png"))); // NOI18N
        lblAdminSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAdminSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminSearchMouseClicked(evt);
            }
        });

        txtLibraryID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLibraryID.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Library ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtLibraryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibraryIDActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtLocation.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLocation.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Location", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });

        txtEstdYear.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtEstdYear.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Estd. Year", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtEstdYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstdYearActionPerformed(evt);
            }
        });

        txtContact.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtContact.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        txtTotalBooks.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtTotalBooks.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Total Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtTotalBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBooksActionPerformed(evt);
            }
        });

        comBoxLibraryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Public", "Private", "Research", "Academic" }));
        comBoxLibraryType.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Library Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        comBoxLibraryType.setOpaque(true);

        comBoxOperatingHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00 - 18:00", "09:00 - 17:00", "17:00 - 02:00" }));
        comBoxOperatingHours.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Operating Hours", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        comBoxOperatingHours.setOpaque(true);

        txtStaffCount.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtStaffCount.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true), "Staff Count", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(164, 148, 108))); // NOI18N
        txtStaffCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffCountActionPerformed(evt);
            }
        });

        btnAddLibrary.setBackground(new java.awt.Color(164, 148, 108));
        btnAddLibrary.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAddLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLibrary.setText(" Add Library");
        btnAddLibrary.setOpaque(true);
        btnAddLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLibraryActionPerformed(evt);
            }
        });

        lblAdminForm.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblAdminForm.setForeground(new java.awt.Color(164, 148, 108));
        lblAdminForm.setText("Form");

        btnUpdateLibrary.setBackground(new java.awt.Color(164, 148, 108));
        btnUpdateLibrary.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpdateLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateLibrary.setText(" Update Library");
        btnUpdateLibrary.setMaximumSize(new java.awt.Dimension(113, 26));
        btnUpdateLibrary.setMinimumSize(new java.awt.Dimension(113, 26));
        btnUpdateLibrary.setPreferredSize(new java.awt.Dimension(113, 26));
        btnUpdateLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLibraryActionPerformed(evt);
            }
        });

        btnDeleteLibrary.setBackground(new java.awt.Color(164, 148, 108));
        btnDeleteLibrary.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteLibrary.setText("Delete Library");
        btnDeleteLibrary.setMaximumSize(new java.awt.Dimension(113, 26));
        btnDeleteLibrary.setMinimumSize(new java.awt.Dimension(113, 26));
        btnDeleteLibrary.setPreferredSize(new java.awt.Dimension(113, 26));
        btnDeleteLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLibraryActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(164, 148, 108));
        btnClear.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        comBoxSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Library ID (Ascending)", "Library ID (Descending)", "Name (Ascending)", "Name (Descending)", "Estd.Year (Ascending)", "Estd.Year (Descending)", "Staff Count (Ascending)", "Staff Count (Descending)", "Total Books (Ascending)", "Total Books (Descending)" }));
        comBoxSortBy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 2, true));
        comBoxSortBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxSortByActionPerformed(evt);
            }
        });

        lblSortBy.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSortBy.setForeground(new java.awt.Color(164, 148, 108));
        lblSortBy.setText("Sort by:");

        javax.swing.GroupLayout pnlMainAdminLayout = new javax.swing.GroupLayout(pnlMainAdmin);
        pnlMainAdmin.setLayout(pnlMainAdminLayout);
        pnlMainAdminLayout.setHorizontalGroup(
            pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPnlAdmin)
                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                        .addComponent(lblAdminDashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSortBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBoxSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainAdminLayout.createSequentialGroup()
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                .addComponent(lblAdminForm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAdminFunctions))
                            .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtLibraryID, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comBoxLibraryType, 0, 165, Short.MAX_VALUE))
                                    .addComponent(txtStaffCount, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                        .addComponent(txtEstdYear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                                        .addComponent(txtTotalBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comBoxOperatingHours, 0, 165, Short.MAX_VALUE))))
                                .addGap(182, 182, 182)
                                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(btnUpdateLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(110, 110, 110)))
                .addContainerGap())
        );
        pnlMainAdminLayout.setVerticalGroup(
            pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comBoxOperatingHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainAdminLayout.createSequentialGroup()
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdminSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAdminDashboard)
                                .addComponent(txtAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comBoxSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSortBy)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdminForm)
                            .addComponent(lblAdminFunctions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLibraryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstdYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoxLibraryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStaffCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMainBottom.setBackground(new java.awt.Color(164, 148, 108));

        lblMainBottomLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMainBottomLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainBottomLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/logout.png"))); // NOI18N
        lblMainBottomLogOut.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 148, 108), 1, true), "Log out", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        lblMainBottomLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMainBottomLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainBottomLogOutMouseClicked(evt);
            }
        });

        lblMainBottomlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/output-onlinepngtools (3).png"))); // NOI18N

        lblMainBottomHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainBottomHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/library (1).png"))); // NOI18N
        lblMainBottomHome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 148, 108)), "Home", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        lblMainBottomHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMainBottomHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainBottomHomeMouseClicked(evt);
            }
        });

        lblMainBottomAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainBottomAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarysystem/resources/admin.png"))); // NOI18N
        lblMainBottomAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 148, 108)), "Admin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        lblMainBottomAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMainBottomAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainBottomAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMainBottomLayout = new javax.swing.GroupLayout(pnlMainBottom);
        pnlMainBottom.setLayout(pnlMainBottomLayout);
        pnlMainBottomLayout.setHorizontalGroup(
            pnlMainBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainBottomlogo)
                .addGap(260, 260, 260)
                .addComponent(lblMainBottomHome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainBottomAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMainBottomLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMainBottomLayout.setVerticalGroup(
            pnlMainBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMainBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMainBottomLogOut)
                    .addComponent(lblMainBottomHome)
                    .addComponent(lblMainBottomAdmin)
                    .addComponent(lblMainBottomlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMainBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMainBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Initializes the library data by creating a list of sample libraries. Adds
     * predefined library objects to the library list and registers them in the
     * system.
     */
    private void initializeData(){
        // Create a new library list to hold LibraryModel objects
        libList = new ArrayList<>();

        // Registering sample libraries
        registerLibrary(new LibraryModel(014, "KTM Library", "Kathmandu", "Public", 1885, "9851060670", 350, 40000, "09:00 - 17:00")); 
        registerLibrary(new LibraryModel(139, "Pokhara Library", "Pokhara", "Research", 2000, "9851068889", 200, 30000, "09:00 - 17:00"));
        registerLibrary(new LibraryModel(800, "Nepal Bharat Library", "Kathmandu", "Public", 2000, "9851038889", 280, 63000, "06:00 - 18:00"));
        registerLibrary(new LibraryModel(118, "Lumbini Library", "Rupandehi", "Academic", 1555, "9851068989", 500, 30000, "06:00 - 18:00"));
        registerLibrary(new LibraryModel(228, "Giratee Library", "Kathmandu", "Private", 2024, "9851080670", 300, 40500, "17:00 - 02:00"));
    }
    /**
     * Registers a new library by adding it to the library list and updating the
     * table view.
     *
     * @param library The LibraryModel object representing the library to be
     * registered.
     */
    private void registerLibrary(LibraryModel library) {
        //Adding the library model object to the library list
        libList.add(library);
        // Update the table model to include the new library details
        DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();
        model.addRow(new Object[]{
            library.getLibID(), library.getLibName(), library.getLocation(), library.getLibType(), library.getEstablishedYear(), library.getContactNumber(), library.getStaffCount(), library.getTotalBooks(), library.getOperatingHours()
        });
    }
    
    /**
     * Initializes the main layout of the application using a CardLayout.
     * Configures the container to switch between different screens.
     */
    private void initializeLayout(){
        // Create and set a new CardLayout for managing the main screens
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);
        
        //Add the panels to the layout with releant identifiers
        getContentPane().add(pnlLoginScreen, "LoginScreen");
        getContentPane().add(pnlMainScreen, "MainScreen");
        //Display the login screen by default
        cardLayout.show(getContentPane(), "LoginScreen");
    }
    
    /**
     * Initializes the layout for the main screen using a CardLayout. Configures
     * the panel to switch between different sections within the main screen.
     */
    private void initializeMainScreenLayout(){
        // Create and set a new CardLayout for managing the main screen's sections
        mainCardLayout = new java.awt.CardLayout();
        pnlMain.setLayout(mainCardLayout);
        
        //Add the panels to the layout with releant identifiers
        pnlMain.add(pnlMainHome, "Home");
        pnlMain.add(pnlMainAdmin, "Admin");
        
        //Display the Home panel by default
        mainCardLayout.show(pnlMain, "Home");
        
    }   
    

/**
 * Sets the values of text fields and combo boxes to the data from the selected row in the table.
 * Ensures that the form displays the details of the selected library record for updating.
 */
    private void setTextFieldsToSelectedRow() {
        // Retrieve the table model from the admin library table
        DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();
        // Get the index of the selected row in the table
        int selectedRow = tblAdminLib.getSelectedRow();
        // Check if a row is selected
        if (selectedRow != -1) {
            // Retrieve values from the selected row
            int libID = (int) model.getValueAt(selectedRow, 0);
            String libName = (String) model.getValueAt(selectedRow, 1);
            String location = (String) model.getValueAt(selectedRow, 2);
            String libType = (String) model.getValueAt(selectedRow, 3);
            int establishedYear = (int) model.getValueAt(selectedRow, 4);
            String contactNumber = (String) model.getValueAt(selectedRow, 5);
            int staffCount = (int) model.getValueAt(selectedRow, 6);
            int totalBooks = (int) model.getValueAt(selectedRow, 7);
            String operatingHours = (String) model.getValueAt(selectedRow, 8);

            // Set text fields to these values
            txtLibraryID.setText(String.valueOf(libID));
            txtName.setText(libName);
            txtLocation.setText(location);
            comBoxLibraryType.setSelectedItem(libType);
            txtEstdYear.setText(String.valueOf(establishedYear));
            txtContact.setText(contactNumber);
            txtStaffCount.setText(String.valueOf(staffCount));
            txtTotalBooks.setText(String.valueOf(totalBooks));
            comBoxOperatingHours.setSelectedItem(operatingHours);
        }
    }

    private void txtLibraryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibraryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibraryIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void txtEstdYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstdYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstdYearActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtTotalBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBooksActionPerformed

    private void txtStaffCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffCountActionPerformed

    /**
     * Handles the action event when the "Add Library" button is clicked.
     * Validates the input fields, checks for duplicate library IDs, and
     * registers a new library if the inputs are valid. Displays appropriate
     * error or success messages based on validation outcomes.
     *
     * @param evt the event triggered when the button is clicked
     */
    private void btnAddLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLibraryActionPerformed

        // Retrieve input values from text fields and combo boxes                                              
        String libId = txtLibraryID.getText();
        String name = txtName.getText();
        String location = txtLocation.getText();
        String libType = (String) comBoxLibraryType.getSelectedItem();
        String estdYear = txtEstdYear.getText();
        String contact = txtContact.getText();
        String staffCount = txtStaffCount.getText();
        String totalBooks = txtTotalBooks.getText();
        String operatingHours = (String) comBoxOperatingHours.getSelectedItem();
        
        // Flag to track validity of input data
        boolean valid = true;
        // To collect error messages
        StringBuilder errors = new StringBuilder();

        // Check for empty fields
        if (Validation.isNullOrEmpty(libId) || Validation.isNullOrEmpty(name)
                || Validation.isNullOrEmpty(location) 
                || Validation.isNullOrEmpty(estdYear) || Validation.isNullOrEmpty(contact)
                || Validation.isNullOrEmpty(staffCount) || Validation.isNullOrEmpty(totalBooks)
                ) {
            errors.append("Please fill the entire form.\n");
        } else {
            try {
                //Check if the library already exists
                for (LibraryModel library : libList) {
                    if (Integer.parseInt(libId) == library.getLibID()) {
                        valid = false;
                    }
                }
                if (valid) {
                    // Perform validation for every field 
                    if (!Validation.isValidLibId(Integer.parseInt(libId))) {
                        errors.append("Library ID must be 3 digits.\n");
                    }
                    if (!Validation.isValidName(name)) {
                        errors.append("Name should only include alphabets.\n");
                    }
                    if (!Validation.isValidLocation(location)) {
                        errors.append("Location should only include alphabets.\n");
                    }
                    if (!Validation.isValidContact(contact)) {
                        errors.append("Contact number should be 10 digits and start with 98.\n");
                    }
                    if (!Validation.isValidTotalBooks(Integer.parseInt(totalBooks))) {
                        errors.append("Total Books must be a positive number.\n");
                    }
                    if (!Validation.isValidStaffCount(Integer.parseInt(staffCount))) {
                        errors.append("Staff Count must be between 1 and 999.\n");
                    }
                    if (!Validation.isValidEstdYear(Integer.parseInt(estdYear))) {
                        errors.append("Established Year must be between 1500 and 2024.\n");
                    }

                } else {
                    // Show a message if the library has already been registered
                    JOptionPane.showMessageDialog(this, "This library is already registered", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                // Handle exception arising from invalid data type
                errors.append("Enter valid numbers where required.\nLibrary ID, Estd.Year, Staff Count & Total Books should be numbers.");
            }
        }

        // Display errors if any
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this, errors.toString(), "Invalid Input", JOptionPane.ERROR_MESSAGE);
        } else if(valid) {
            // If valid, register the library
            registerLibrary(new LibraryModel(
                    Integer.parseInt(libId), name, location, libType,
                    Integer.parseInt(estdYear), contact,
                    Integer.parseInt(staffCount), Integer.parseInt(totalBooks), operatingHours));
            // Display success message to the user
            JOptionPane.showMessageDialog(this, "Library added successfully!", "Add Successful", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnAddLibraryActionPerformed

    /**
     * Handles the action event when the "Log In" button is clicked. Validates
     * the username and password, displays error messages for invalid inputs,
     * and transitions to the main screen upon successful login.
     *
     * @param evt the event triggered when the button is clicked
     */
    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // Get the username and password input
        String username = txtLoginUsername.getText();
        String password = new String(pwdLoginPassword.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            lblLoginError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            
        cardLayout.show(getContentPane(), "MainScreen");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    /**
     * Handles the mouse click event on the "Log Out" label. Navigates back to
     * the login screen and clears the username and password fields.
     *
     * @param evt the event triggered when the label is clicked
     */
    private void lblMainBottomLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainBottomLogOutMouseClicked
        // Switch back to the login screen
        cardLayout.show(getContentPane(), "LoginScreen");
        
        //Clear the username and password fields
        txtLoginUsername.setText("");
        pwdLoginPassword.setText("");
    }//GEN-LAST:event_lblMainBottomLogOutMouseClicked

    /**
     * Handles the mouse click event on the "Home" label. Displays the "Home"
     * panel within the main screen.
     *
     * @param evt the event triggered when the label is clicked
     */
    private void lblMainBottomHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainBottomHomeMouseClicked
        //Show the home panel
        mainCardLayout.show(pnlMain, "Home");
    }//GEN-LAST:event_lblMainBottomHomeMouseClicked

    /**
     * Handles the mouse click event on the "Admin" label. Displays the "Admin"
     * panel within the main screen.
     *
     * @param evt the event triggered when the label is clicked
     */
    private void lblMainBottomAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainBottomAdminMouseClicked
        // Show the admin panel
        mainCardLayout.show(pnlMain, "Admin");
    }//GEN-LAST:event_lblMainBottomAdminMouseClicked

    /**
     * Handles the action event when the "Update Library" button is clicked.
     * Validates the input data, updates the selected library record in the
     * ArrayList and table, and displays appropriate messages for errors or
     * successful updates.
     *
     * @param evt the event triggered when the button is clicked
     */
    private void btnUpdateLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLibraryActionPerformed

    // Retrieve the model and selected row index                                                    
    DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();
    int selectedRow = tblAdminLib.getSelectedRow();

    //Check if a row is selected
    if (selectedRow != -1) {
        // Retrieve updated values from text fields and combo boxes
        String libId = txtLibraryID.getText();
        String name = txtName.getText();
        String location = txtLocation.getText();
        String libType = (String) comBoxLibraryType.getSelectedItem();
        String estdYear = txtEstdYear.getText();
        String contact = txtContact.getText();
        String staffCount = txtStaffCount.getText();
        String totalBooks = txtTotalBooks.getText();
        String operatingHours = (String) comBoxOperatingHours.getSelectedItem();

        //Flag for input validation
        boolean valid = true;
        // Collect error messages
        StringBuilder errors = new StringBuilder(); 

        // Check for empty fields
        if (Validation.isNullOrEmpty(libId) || Validation.isNullOrEmpty(name)
                || Validation.isNullOrEmpty(location) 
                || Validation.isNullOrEmpty(estdYear) || Validation.isNullOrEmpty(contact)
                || Validation.isNullOrEmpty(staffCount) || Validation.isNullOrEmpty(totalBooks)) {
            errors.append("Please fill the entire form.\n");
            valid = false;
        } else {
            try {
                // Perform validation for every field
                if (!Validation.isValidLibId(Integer.parseInt(libId))) {
                    errors.append("Library ID must be 3 digits.\n");
                }
                if (!Validation.isValidName(name)) {
                    errors.append("Name should only include alphabets.\n");
                }
                if (!Validation.isValidLocation(location)) {
                    errors.append("Location should only include alphabets.\n");
                }
                if (!Validation.isValidContact(contact)) {
                    errors.append("Contact number should be 10 digits and start with 98.\n");
                }
                if (!Validation.isValidTotalBooks(Integer.parseInt(totalBooks))) {
                    errors.append("Total Books must be a positive number.\n");
                }
                if (!Validation.isValidStaffCount(Integer.parseInt(staffCount))) {
                    errors.append("Staff Count must be between 1 and 999.\n");
                }
                if (!Validation.isValidEstdYear(Integer.parseInt(estdYear))) {
                    errors.append("Established Year must be between 1500 and 2024.\n");
                }
            } catch (NumberFormatException ex) {
                // Handle exception arising from invalid data type
                errors.append("Enter valid numbers where required.\nLibrary ID, Estd.Year, Staff Count & Total Books should be numbers.");
                valid = false;
            }
        }

        // Display errors if any
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this, errors.toString(), "Invalid Input", JOptionPane.ERROR_MESSAGE);
        } else if (valid) {
            
            // If valid, update the library
            LibraryModel updatedLibrary = new LibraryModel(
                    Integer.parseInt(libId), name, location, libType,
                    Integer.parseInt(estdYear), contact,
                    Integer.parseInt(staffCount), Integer.parseInt(totalBooks), operatingHours);

            // Replace the old object in the ArrayList
            libList.set(selectedRow, updatedLibrary);

            // Update the table row
            model.setValueAt(libId, selectedRow, 0);
            model.setValueAt(name, selectedRow, 1);
            model.setValueAt(location, selectedRow, 2);
            model.setValueAt(libType, selectedRow, 3);
            model.setValueAt(estdYear, selectedRow, 4);
            model.setValueAt(contact, selectedRow, 5);
            model.setValueAt(staffCount, selectedRow, 6);
            model.setValueAt(totalBooks, selectedRow, 7);
            model.setValueAt(operatingHours, selectedRow, 8);

            // Display success message to the user
            JOptionPane.showMessageDialog(this, "Library updated successfully!", "Update Successful", JOptionPane.INFORMATION_MESSAGE);

        }
        
    } else {
        // If no row is selected, display a warning message
        JOptionPane.showMessageDialog(this, "Please select a row to update.", "No Selection", JOptionPane.WARNING_MESSAGE);
    }


    }//GEN-LAST:event_btnUpdateLibraryActionPerformed

    /**
     * Handles the action event when the "Delete Library" button is clicked.
     * Deletes the selected library record from the table and the ArrayList.
     *
     * @param evt the event triggered when the button is clicked
     */
    private void btnDeleteLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLibraryActionPerformed
        // Get the selected row index from the table
        int selectedRow = tblAdminLib.getSelectedRow();

        // Check if a row is selected
        if (selectedRow != -1) {
            // Retrieve the table model and remove the selected row and from the array list
            DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();
            model.removeRow(selectedRow);
            libList.remove(selectedRow);
            
            // Notify the user that the deletion was successful
            JOptionPane.showMessageDialog(this, "Library deleted successfully!", "Delete Successful", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // If no row is selected, display a warning message
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "No Selection", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnDeleteLibraryActionPerformed

    /**
     * Handles the action event when the "Clear" button is clicked. Clears all
     * the input fields in the library form.
     *
     * @param evt the event triggered when the button is clicked
     */
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
            //Reset all input fields to empty strings
            txtLibraryID.setText("");
            txtName.setText("");
            txtLocation.setText("");
            txtEstdYear.setText("");
            txtContact.setText("");
            txtStaffCount.setText("");
            txtTotalBooks.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * Handles the action when a sorting option is selected from the combo box.
     * Sorts the `libList` using the appropriate sorting algorithm based on the
     * selected option and updates the table display with the sorted data.
     *
     * @param evt the event triggered when an item is selected in the combo box
     */
    private void comBoxSortByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxSortByActionPerformed

        // Get the selected sorting option from the combo box
        String item = (String)comBoxSortBy.getSelectedItem();
        
        // Determine the sorting algorithm to use based on the selected option
        if (item.equals("Total Books (Ascending)") || item.equals("Total Books (Descending)") || item.equals("Staff Count (Ascending)") || item.equals("Staff Count (Descending)")){
            SelectionSort.selectionSort(libList, item);     
        }else if(item.equals("Library ID (Ascending)") || item.equals("Library ID (Descending)") || item.equals("Estd.Year (Ascending)") || item.equals("Estd.Year (Descending)")){
            InsertionSort.insertionSort(libList, item);
        }else{
            MergeSort.sort(libList, item);
        }

        // Clear the existing table data
        DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();
        model.setRowCount(0);
        
        //Populate the table with the sorted list
        for(LibraryModel library : libList){
            model.addRow(new Object[]{
            library.getLibID(), library.getLibName(), library.getLocation(), library.getLibType(), library.getEstablishedYear(), library.getContactNumber(), library.getStaffCount(), library.getTotalBooks(), library.getOperatingHours()
        });
        }
    }//GEN-LAST:event_comBoxSortByActionPerformed

    /**
     * Handles the action when the search label is clicked. Searches for a
     * library by name using binary search and highlights the matching row in
     * the table.
     *
     * @param evt the event triggered when the search label is clicked
     */
    private void lblAdminSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminSearchMouseClicked
        // Sort the list by name in ascending order for binary search
        MergeSort mergeSort = new MergeSort();
        List<LibraryModel> sortedList = mergeSort.sort(libList, "Name (Ascending)");
        
        // Perform binary search to find the library by name
        BinarySearch search = new BinarySearch();
        LibraryModel searchedData = search.searchByName(txtAdminSearch.getText().trim(), sortedList, 0, sortedList.size()-1);
        
        if (isNullOrEmpty(txtAdminSearch.getText())) {
            JOptionPane.showMessageDialog(this, "Please fill the search bar before searching.", "Invalid Input.", JOptionPane.WARNING_MESSAGE);
        } else if (searchedData != null) {
            // Find the row in the table that matches the searched data
            DefaultTableModel model = (DefaultTableModel) tblAdminLib.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {

                if (model.getValueAt(i, 1).equals(searchedData.getLibName())) {
                    // Select and highlight the row
                    tblAdminLib.setRowSelectionInterval(i, i);
                    tblAdminLib.scrollRectToVisible(tblAdminLib.getCellRect(i, 0, true));
                    break;
                }
            }
        } else {
            // Display a warning message if the library is not found
            JOptionPane.showMessageDialog(this, "Sorry! The library you are searching is not registered.", "Search Result Not Found.", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_lblAdminSearchMouseClicked

    /**
     * Handles the event when a row in the table is clicked. Updates the text
     * fields in the form with the data from the selected row.
     *
     * @param evt the event triggered when the table is clicked
     */
    private void tblAdminLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminLibMouseClicked
        // Single-click detection
        if (evt.getClickCount() == 1) { 
            // Set the form's text fields to the data from the selected row
            setTextFieldsToSelectedRow();
        }
    }//GEN-LAST:event_tblAdminLibMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLibrary;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteLibrary;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnUpdateLibrary;
    private javax.swing.JComboBox<String> comBoxLibraryType;
    private javax.swing.JComboBox<String> comBoxOperatingHours;
    private javax.swing.JComboBox<String> comBoxSortBy;
    private javax.swing.JLabel lblAdminDashboard;
    private javax.swing.JLabel lblAdminForm;
    private javax.swing.JLabel lblAdminFunctions;
    private javax.swing.JLabel lblAdminSearch;
    private javax.swing.JLabel lblHomeDesc;
    private javax.swing.JLabel lblHomeDescTitle;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginLogo;
    private javax.swing.JLabel lblMainBottomAdmin;
    private javax.swing.JLabel lblMainBottomHome;
    private javax.swing.JLabel lblMainBottomLogOut;
    private javax.swing.JLabel lblMainBottomlogo;
    private javax.swing.JLabel lblSortBy;
    private javax.swing.JPanel pnlHomeDesc;
    private javax.swing.JPanel pnlLoginCenter;
    private javax.swing.JPanel pnlLoginScreen;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainAdmin;
    private javax.swing.JPanel pnlMainBottom;
    private javax.swing.JPanel pnlMainHome;
    private javax.swing.JLabel pnlMainHomeLogo;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPasswordField pwdLoginPassword;
    private javax.swing.JScrollPane scrPnlAdmin;
    private javax.swing.JTable tblAdminLib;
    private javax.swing.JTextField txtAdminSearch;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEstdYear;
    private javax.swing.JTextField txtLibraryID;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStaffCount;
    private javax.swing.JTextField txtTotalBooks;
    // End of variables declaration//GEN-END:variables
}
